### ISSUE TITLE
Perl problem

### ISSUE THREAD

**Issue by alexjoni** [kettenbach-it/FHEM-TPLink-HS110#5]
Hi,

having some issues with a HS100:

2018.02.11 21:44:24 1: reload: Error:Modul 24_TPLinkHS110 deactivated:
 Type of arg 1 to keys must be hash (not array dereference) at ./FHEM/24_TPLinkHS110.pm line 182, near "}) "
It's probably because of my ancient perl:
root@LG-NAS:/opt/fhem-5.3/FHEM> perl --version
This is perl, v5.10.0 built for arm-linux-gnueabi-thread-multi
Copyright 1987-2007, Larry Wall

I commented out lines 182..186 (I don't have a HS110 so I don't really need the 'emeter' stats) and the module works for me. ($Id: 24_TPLinkHS110.pm 16060 2018-02-01 13:02:36Z vk $)
There is probably a better fix though..

Regards,
Alex

**Comment by kettenbach-it** [comment]
Could you please to replace line 182 by:

`foreach my $key (sort 0.. $#{$json->{'emeter'}->{'get_daystat'}->{'day_list'}}) {`

If it works with your old perl and with m recent perl, I might put it into the offical code. 
Maybe....

Since the last release of Perl in the 5.10 series was in 2009, so I'd recommend is that you look into upgrading your Perl. Would be a the much better solution.
